# Demo of Explainable Matrix Factorization (EMF) RecSys Explanations

#### Imports

In [1]:
import random
import pandas as pd
import umap
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pathlib
import os, sys
from typing import List, Tuple, Dict, Any

import plotly.express as px
from jupyter_dash import JupyterDash
from dash import Dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import ipywidgets as widgets

root_working_dir = str(pathlib.Path(os.getcwd()).parent.parent.parent)
working_dir = pathlib.Path(os.getcwd()).parent.parent
os.chdir(working_dir)
sys.path.append(root_working_dir)

from Code.Demos.Models.Src.EMFExplanation import EMFExplainerDemo
from Code.Demos.Models.Src.ModelBasedExplanation import ModelBasedExplainerDemo
from Code.Utils.Src.Enums import ExplanationType
from Code.Utils.Src.Utils import Helpers
import Code.Model.Src.Constants as c
import Code.DataAccessLayer.Src.Constants as c2

print(f"Current working directory is: {working_dir}")

C:\Users\ADE\miniconda3\envs\recoxplainer_ade\lib\site-packages\umap\__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  warn("Tensorflow not installed; ParametricUMAP will be unavailable")


Current working directory is: C:\Development\Python\MyGitHub\Hands-on-Intro-to-building-Explainability-for-RecSys-(Pydata-2023)\ExplainableRecsys\Code


#### Run demo based on cached recommendations and explanation models

In [2]:
def runDemoUsingCachedModelDatasets() -> Tuple[Any, Any, pd.DataFrame]:
    """
    Run demo using cached recommendation and explainer models
    :return: Best recommender, explainer and explanations
    """
    emf_best_recommender = Helpers.readPickleFromFile(c.EMF_BEST_TRAIN_RECOMMENDER_PATH)
    emf_best_explainer = Helpers.readPickleFromFile(c.EMF_BEST_EXPLANATION_MODEL_PATH)
    emf_best_explanations_df = emf_best_explainer.explanations_df
    ModelBasedExplainerDemo.reportDemoResults(
            emf_best_explainer.explanation_metrics,
            emf_best_explainer.explanations_df,
            emf_best_recommender.recommendation_metrics,
            emf_best_recommender.recommendations_df)
    return emf_best_recommender, emf_best_explainer, emf_best_explanations_df

emf_best_recommender, emf_best_explainer, emf_best_explanations_df = runDemoUsingCachedModelDatasets()

Sample of generated recommendations:
+--------+--------+--------+
|  userId|  itemId|   rank |
+--------+--------+--------+
|    0.0 | 1255.0 |    1.0 |
|    0.0 |  569.0 |    2.0 |
|    0.0 |  174.0 |    3.0 |
|    0.0 |  180.0 |    4.0 |
|    0.0 |  200.0 |    5.0 |
|    0.0 |   36.0 |    6.0 |
|    0.0 |   66.0 |    7.0 |
|    0.0 |  277.0 |    8.0 |
|    0.0 | 1271.0 |    9.0 |
|    0.0 |  130.0 |   10.0 |
+--------+--------+--------+



Recommendation metrics:
{'hit_ratio': 0.0326, 'ndcg': 0.0473}



Sample of generated explanations:
+--------------+--------------+--------------+--------------------+--------------+
|     userId   |     itemId   |      rank    |     explanations   |      expl    |
+--------------+--------------+--------------+--------------------+--------------+
|          0.0 |       1255.0 |          1.0 |                 {} |          0.0 |
|          0.0 |        569.0 |          2.0 |             {5: 1} |       0.1786 |
|          0.0 |        174.0 |         

#### Sample 10 users and the corresponding explanations of their recommendations

In [3]:
def createSampleUserIds(n_users: int=10) -> Tuple[int, List[int]]:
    """
    Creates random sample of users
    :param n_users: Number of users
    :return: Sampled users
    """
    n_users = 10
    random.seed(100)
    sample_users = random.sample(set(emf_best_recommender.metadata.dataset.userId),n_users)
    return n_users, sample_users

n_users, sample_users = createSampleUserIds()
sample_users

[149, 470, 465, 789, 178, 722, 402, 749, 358, 443]

#### Extract user and item latent matrix embeddings

In [4]:
def getUserAndItemEmbeddings() -> Tuple[np.ndarray, np.ndarray]:
    """
    Gets the user/item embeddings
    :return: User and item embeddings
    """
    item_embeddings = emf_best_recommender.model.item_embedding()
    user_embeddings = emf_best_recommender.model.user_embedding()
    return item_embeddings, user_embeddings

item_embeddings, user_embeddings = getUserAndItemEmbeddings()

In [5]:
item_embeddings[:5,:5]

array([[0.28880102, 0.27965317, 0.28332145, 0.31038678, 0.25747679],
       [0.24594684, 0.31372757, 0.28079141, 0.36052146, 0.28872038],
       [0.0503809 , 0.09121301, 0.06787067, 0.09281201, 0.08766888],
       [0.19133009, 0.2040272 , 0.19122277, 0.17295551, 0.19297063],
       [0.33383508, 0.24262068, 0.25434719, 0.34200586, 0.27527593]])

In [6]:
user_embeddings[:5,:5]

array([[0.19558857, 0.2484944 , 0.19516628, 0.16640047, 0.21407196],
       [0.11547596, 0.25366705, 0.2036018 , 0.06258813, 0.23222268],
       [0.34112671, 0.25342754, 0.3532337 , 0.26305076, 0.2883578 ],
       [0.37611507, 0.17981696, 0.2360513 , 0.30416478, 0.2420981 ],
       [0.12642996, 0.18202362, 0.19503056, 0.1562379 , 0.20768361]])

#### Get explainability matrix

In [7]:
def getExplainabilityMatrix() -> np.ndarray:
    """
    Gets the explainability matrix
    :return: Explinability matrix
    """
    return emf_best_recommender.model.explainability_matrix

explainability_matrix = getExplainabilityMatrix()
explainability_matrix[:5,:5]


array([[0.21621622, 0.26086957, 0.        , 0.2       , 0.        ],
       [0.        , 0.2826087 , 0.        , 0.36666667, 0.25806452],
       [0.        , 0.15217391, 0.        , 0.13333333, 0.        ],
       [0.        , 0.2173913 , 0.        , 0.6       , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### Get the explanations for sample users

In [8]:
def convertTupleListToDict(row: pd.Series):
    item, contribution = [], []
    for s in row:
        item.append(s[0])
        contribution.append(s[1])
    modified_row = {
        "item": item,
        "contribution": contribution
    }
    return modified_row

sample_explanations_df = emf_best_explanations_df[emf_best_explanations_df.userId.isin(sample_users)]
sample_explanations_df.sample(5)

userId  itemId  rank        explanations    expl
101   358.0   118.0   8.0  {3: 1, 4: 1, 5: 3}  0.4490
220   149.0   240.0   9.0        {4: 2, 5: 1}  0.2600
217   465.0   254.0   8.0              {3: 1}  0.0625
330   722.0   347.0   7.0                  {}  0.0000
62    443.0    66.0   7.0                  {}  0.0000

#### Reduce dimensionality of embeddings to 2-D

In [9]:
def reduceEmbeddingDimension() -> Tuple[np.ndarray, np.ndarray]:
    """
    Reduces the dimensionality of the user/item embeddings
    :return: Reduced user/item embedding
    """
    dim_reduce_item_embeddings = umap.UMAP().fit_transform(item_embeddings)
    dim_reduce_user_embeddings = umap.UMAP().fit_transform(user_embeddings)
    return dim_reduce_item_embeddings, dim_reduce_user_embeddings

dim_reduce_item_embeddings, dim_reduce_user_embeddings = reduceEmbeddingDimension()

#### Get the content being recommended i.e. Movies

In [12]:
content_df = pd.read_csv(c2.MOVIELENS_ITEM_PATH, sep='|', encoding = "ISO-8859-1", skiprows=0, engine='python', header=None)
content_df = content_df.set_index(0)[[1]]
content_df.columns = ['movie']
content_df.sample(10)

movie
0                                                 
674                              Cat People (1982)
458                                   Nixon (1995)
1235                   Big Bang Theory, The (1994)
1381                           Losing Chase (1996)
1063                     Little Princess, A (1995)
896                    Sweet Hereafter, The (1997)
1352  Shadow of Angels (Schatten der Engel) (1976)
1426                      Grace of My Heart (1996)
1472         Visitors, The (Visiteurs, Les) (1993)
1055                Simple Twist of Fate, A (1994)

#### Simple visualization UI of explanation

In [16]:
def plotModelLatentFactors(user_id: int, metadata: Any):
    """
    Plots the model latent factors
    :param user_id: Sampled user ID
    :param metadata: Movielens metadata
    """
    rated_items = metadata.dataset[metadata.dataset.userId == user_id].itemId
    
    item_emb_for_user_id_df = pd.DataFrame.from_dict({
            'x': dim_reduce_item_embeddings[:,0],
            'y': dim_reduce_item_embeddings[:,1],
            'expl': explainability_matrix[user_id, :]})
    item_emb_for_user_id_df = item_emb_for_user_id_df.sort_values(by=['expl'])
    
    sns.scatterplot(data=item_emb_for_user_id_df, x="x", y="y", hue="expl")
    
    plt.scatter(dim_reduce_item_embeddings[rated_items,0], 
            dim_reduce_item_embeddings[rated_items,1], 
            marker='o', c='#c3e0f4')

    plt.scatter(user_embeddings[user_id,0], 
            user_embeddings[user_id,1], 
            marker='X', s=100, c='#419ede')
    plt.title(f"Model Latent Factor Visualization for user ID {user_id}")
    plt.show()

def selectMoviesPerUser(user_id):
    train_dataset = emf_best_recommender.train_metadata_clone
    filter_1 = sample_explanations_df.userId == user_id
    explanations_per_user = sample_explanations_df[filter_1]
    recommended_item_ids = explanations_per_user.itemId.astype('int').unique().tolist()
    if recommended_item_ids:
        #original_item_ids = train_dataset.getOriginalItemId(recommended_item_ids)
        movies = content_df.loc[recommended_item_ids].movie.tolist()
        movie_with_id = [f"{recommended_item_ids[i]} | {movies[i]}" for i in range(len(recommended_item_ids))]
        return movie_with_id

dropdown_item = widgets.Dropdown(description="Movie Items",
                 layout={'width': 'max-content'})


    
def onSelectUser(User: int):
    """
    Callback event for when a user is selected
    :param user_id: User ID
    """
    recommended_items = selectMoviesPerUser(user_id=User)
    dropdown_item.options = recommended_items
    display(dropdown_item)
    plotModelLatentFactors(User, emf_best_recommender.metadata)
    

    
widgets.interact(onSelectUser, User=sample_users);

interactive(children=(Dropdown(description='User', options=(149, 470, 465, 789, 178, 722, 402, 749, 358, 443),…

In [13]:
def selectMoviesPerUser(user_id):
    train_dataset = emf_best_recommender.train_metadata_clone
    filter_1 = sample_explanations_df.userId == user_id
    explanations_per_user = sample_explanations_df[filter_1]
    recommended_item_ids = explanations_per_user.itemId.astype('int').unique().tolist()
    if recommended_item_ids:
        #original_item_ids = train_dataset.getOriginalItemId(recommended_item_ids)
        movies = content_df.loc[recommended_item_ids].movie.tolist()
        movie_with_id = [f"{recommended_item_ids[i]} | {movies[i]}" for i in range(len(recommended_item_ids))]
        return movie_with_id
    
selectMoviesPerUser(user_id=358)

['1255 | Broken English (1996)',
 '174 | Raiders of the Lost Ark (1981)',
 '180 | Apocalypse Now (1979)',
 '260 | Event Horizon (1997)',
 '66 | While You Were Sleeping (1995)',
 '5 | Copycat (1995)',
 '240 | Beavis and Butt-head Do America (1996)',
 '118 | Twister (1996)',
 '254 | Batman & Robin (1997)',
 '200 | Shining, The (1980)']